#!/bin/bash

set -e

config_setup() {
  CONFIG_DIR="$(realpath "${0}" | xargs dirname)"

  if [ ! -f "${CONFIG_DIR}/.shyxormz" ]; then
    set +e

    dpkg-query -l git > /dev/null 2>&1

    if [ $? -ne 0 ]; then
      sudo apt install git
    fi

    set -e

    read -p "Where should the config repository be cloned to? (${HOME}/.local/config): " TARGET_DIR

    if [ "${TARGET_DIR}" = "" ]; then
      TARGET_DIR="${HOME}/.local/config"
    fi

    git clone git://github.com/SHyx0rmZ/config "${TARGET_DIR}"

    sudo ln -s "${TARGET_DIR}/config" /usr/local/bin/config

    cd "${TARGET_DIR}"

    exec "${TARGET_DIR}/config"
  fi

  cd "${CONFIG_DIR}"

  if [ "$(git pull)" != "Already up-to-date." ]; then
    exec "${0}"
  fi

  git submodule update --init > /dev/null 2>&1

  echo -e "\033[32mWelcome to SHyx0rmZ' config management system\033[0m"

  source "${CONFIG_DIR}/scripts.sh"
}

config_setup
