#!/bin/bash

set -e

apt_maybe_install() {
  echo $- | grep e > /dev/null

  local ERR_STATUS=$?

  if [ ${ERR_STATUS} -eq 0 ]; then
    set +e
  fi

  dpkg-query -l "${1}" > /dev/null 2>&1

  if [ $? -ne 0 ]; then
    sudo apt install "${1}"
  fi

  if [ ${ERR_STATUS} -eq 0 ]; then
    set -e
  fi
}

provide_basics() {
  if [ ! -f "$(realpath "${0}" | xargs dirname)/.shyxormz" ]; then
    set +e

    dpkg-query -l git > /dev/null 2>&1

    if [ $? -ne 0 ]; then
      sudo apt install git
    fi

    set -e

    read -p "Where should the config repository be cloned to? (${HOME}/.local/config): " TARGET_DIR

    if [ "${TARGET_DIR}" = "" ]; then
      TARGET_DIR="${HOME}/.local/config"
    fi

    git clone git://github.com/SHyx0rmZ/config "${TARGET_DIR}"

    sudo ln -s "${TARGET_DIR}/config" /usr/local/bin/config

    cd "${TARGET_DIR}"

    exec "${TARGET_DIR}/config"
  fi

  if [ "$(git pull)" != "Already up-to-date." ]; then
    exec "${0}"
  fi

  echo -e "\033[32mWelcome to SHyx0rmZ' config management system\033[0m"

  for package in git htop iftop iotop ltrace strace vim; do
    apt_maybe_install "${package}"
  done
}

provide_basics
